name: rubocop-todo-corrector

on:
  workflow_dispatch:
    inputs:
      cop_name:
        description: Pass cop name if you want to pick a specific cop.
        required: false
        type: string

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: r7kamura/rubocop-todo-corrector@v0.19.1
        with:
          cop_name: ${{ inputs.cop_name }}
          mode: least_occurred
