name: "RuboCop Challenge"

on:
  workflow_dispatch:
  schedule:
    - cron: 10 3 * * 4
jobs:
  create-rubocop-challenger-pr:
    name: Create Rubocop Challenger Pull Request
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true
      - name: Set git configuration
        run: git config remote.origin.url "git@git@github.com:nobu09/photo-app.git" 
      - name: Create RuboCop challenge pull request
        env:
          GITHUB_ACCESS_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gem install rubocop_challenger
          rubocop_challenger go --email="rubocop-challenger@example.com" --name="Rubocop Challenger" --mode=random --only-exclude
